------------------------------------
--- PASO N° 06 | CLAUSULA EXISTS ---
------------------------------------

SELECT 
    DEP.ID_DEPARTAMENTO COD_DEPTO,
    DEP.DESCRIPCION DEPTO,
    EMP.RUT, 
    EMP.NOMBRE_EMP,
    EMP.ID_EMPLEADO
FROM
    T_DEPARTAMENTO DEP,
    T_EMPLEADO EMP
WHERE EMP.ID_DEPARTAMENTO = :PIN_ID_DEPARTAMENTO
    AND EMP.IND_ESTADO_EMPLEADO = 9 -- 9= ASCENDIDOS
    AND DEP.ID_DEPARTAMENTO = EMP.ID_DEPARTAMENTO

SELECT * FROM T_EMPLEADO

SELECT * FROM T_EVALUACION


SELECT 
    DEP.ID_DEPARTAMENTO COD_DEPTO,
    DEP.DESCRIPCION DEPTO,
    EMP.RUT, 
    EMP.NOMBRE_EMP,
    EMP.ID_EMPLEADO
FROM
    T_DEPARTAMENTO DEP,
    T_EMPLEADO EMP
WHERE EMP.ID_DEPARTAMENTO = :PIN_ID_DEPARTAMENTO
    AND EMP.IND_ESTADO_EMPLEADO = 9 -- 9= ASCENDIDOS
    AND DEP.ID_DEPARTAMENTO = EMP.ID_DEPARTAMENTO
    AND NOT EXISTS (SELECT 1
                    FROM T_EVALUACION EVA
                    WHERE EVA.ID_EMPLEADO = EMP.ID_EMPLEADO )
