-------------------------------------
--- PASO N° 03 | CAMPOS VIRTUALES ---
-------------------------------------

SELECT
    COUNT(ID_EMPLEADO) CANTIDAD,
    SUM(DIAS_TRAB) DIAS_TRABAJADOS
FROM T_EMPLEADO


SELECT
    DAT.TITULO,
    DAT.ORDEN,
    DAT.ID_DEPARTAMENTO,
    DAT.NOMBRE_DEP
FROM (
    SELECT
        'DEPTO NUEVO' TITULO,
        2 ORDEN,
        DEP.ID_DEPARTAMENTO,
        DEP.DESCRIPCION NOMBRE_DEP
    FROM T_DEPARTAMENTO DEP
    WHERE DEP.ID_DEPARTAMENTO = 101
    UNION ALL
    SELECT
        'DEPTO ANTIGUO' TITULO,
        DECODE(EMP.IND_ESTADO_CIVIL,'1',1,'2',1,'3',3,'4',3) ORDEN,
        DEP.ID_DEPARTAMENTO,
        DEP.DESCRIPCION NOMBRE_DEP
    FROM 
        T_EMPLEADO EMP,
        T_DEPARTAMENTO DEP
    WHERE DEP.ID_DEPARTAMENTO = 103
        AND EMP.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
    ) DAT
ORDER BY
    DAT.ORDEN
        