-----------------------------------
--- PASO N° 05 | CLAUSULA UNION ---
-----------------------------------

SELECT * FROM T_EMPLEADO EMP
WHERE EMP.EDAD ---BETWEEN 21 AND 25
               --BETWEEN 26 AND 30
                > 30
                

SELECT
    'GRUPO 1' GRUPO,
    DEP.ID_DEPARTAMENTO DEPTO,
    DEP.DESCRIPCION NOMBRE_DEP,
    EMP.NOMBRE_EMP,
    EMP.EDAD,
    CIV.NOM_ESTADO_CIVIL ESTADO_CIVIL
FROM 
    T_ESTADO_CIVIL CIV,
    T_EMPLEADO EMP, 
    T_DEPARTAMENTO DEP
WHERE DEP.ID_DEPARTAMENTO = :PIN_ID_DEPARTAMENTO
    AND EMP.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
    AND EMP.EDAD BETWEEN 21 AND 25
    AND EMP.IND_ESTADO_CIVIL = 1 --1= SOLTERO
    AND CIV.ID_ESTADO_CIVIL = EMP.IND_ESTADO_CIVIL
UNION
SELECT
    'GRUPO 2' GRUPO,
    DEP.ID_DEPARTAMENTO DEPTO,
    DEP.DESCRIPCION NOMBRE_DEP,
    EMP.NOMBRE_EMP,
    EMP.EDAD,
    CIV.NOM_ESTADO_CIVIL ESTADO_CIVIL
FROM 
    T_ESTADO_CIVIL CIV,
    T_EMPLEADO EMP, 
    T_DEPARTAMENTO DEP
WHERE DEP.ID_DEPARTAMENTO = :PIN_ID_DEPARTAMENTO
    AND EMP.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
    AND EMP.EDAD BETWEEN 26 AND 30
    AND EMP.IND_ESTADO_CIVIL = 2 -- 2= CASADO
    AND CIV.ID_ESTADO_CIVIL = EMP.IND_ESTADO_CIVIL
UNION ALL
SELECT
    'GRUPO 3' GRUPO,
    DEP.ID_DEPARTAMENTO DEPTO,
    DEP.DESCRIPCION NOMBRE_DEP,
    EMP.NOMBRE_EMP,
    EMP.EDAD,
    CIV.NOM_ESTADO_CIVIL ESTADO_CIVIL
FROM 
    T_ESTADO_CIVIL CIV,
    T_EMPLEADO EMP, 
    T_DEPARTAMENTO DEP
WHERE DEP.ID_DEPARTAMENTO = :PIN_ID_DEPARTAMENTO
    AND EMP.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
    AND EMP.EDAD > 30
    AND EMP.IND_ESTADO_CIVIL IN (1,2) -- 1= SOLTERO, 2= CASADO;
    AND CIV.ID_ESTADO_CIVIL = EMP.IND_ESTADO_CIVIL
