--------------------------------------
--- PASO N° 02 | CLAUSULA GROUP BY ---
--------------------------------------

SELECT
    DEP.DESCRIPCION DEPARTAMENTO,
    EMP.NOMBRE_EMP EMPLEADO,
    TAR.FECHA_TAREA,
    TAR.ID_TAREAS_EMPLEADO,
    TAR.NOMBRE_TAREA
FROM 
    T_DEPARTAMENTO DEP, 
    T_EMPLEADO EMP, 
    T_TAREAS_EMPLEADO TAR
WHERE TAR.FECHA_TAREA BETWEEN TO_DATE('01-01-2020','dd-mm-yyyy') AND TO_DATE('31-03-2020','dd-mm-yyyy')
    AND EMP.ID_EMPLEADO = TAR.ID_EMPLEADO
    AND DEP.ID_DEPARTAMENTO = EMP.ID_DEPARTAMENTO
--    AND EMP.ID_EMPLEADO=2


SELECT
    DEP.DESCRIPCION DEPARTAMENTO,
    EMP.NOMBRE_EMP EMPLEADO,
    TO_CHAR(TAR.FECHA_TAREA,'MM-YYYY') MES_ANHO,
    COUNT(TAR.ID_TAREAS_EMPLEADO) CANT_TAREAS
FROM 
    T_DEPARTAMENTO DEP, 
    T_EMPLEADO EMP, 
    T_TAREAS_EMPLEADO TAR
WHERE TAR.FECHA_TAREA BETWEEN TO_DATE('01-01-2020','dd-mm-yyyy') AND TO_DATE('31-03-2020','dd-mm-yyyy')
    AND EMP.ID_EMPLEADO = TAR.ID_EMPLEADO
    AND DEP.ID_DEPARTAMENTO = EMP.ID_DEPARTAMENTO
GROUP BY
    DEP.DESCRIPCION,
    EMP.NOMBRE_EMP,
    TO_CHAR(TAR.FECHA_TAREA,'MM-YYYY') 
ORDER BY
    DEP.DESCRIPCION,
    EMP.NOMBRE_EMP,
    TO_CHAR(TAR.FECHA_TAREA,'MM-YYYY') 

    