--------------------------------------
--- PASO N° 04 | CLAUSULA DISTINCT ---
--------------------------------------

SELECT 
    DEP.ID_DEPARTAMENTO CODIGO_DEP, 
    DEP.DESCRIPCION NOMBRE_DEP,
    EMP.IND_ESTADO_CIVIL,
    CIV.NOM_ESTADO_CIVIL
FROM 
    T_ESTADO_CIVIL CIV,
    T_EMPLEADO EMP, 
    T_DEPARTAMENTO DEP
WHERE EMP.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
    AND CIV.ID_ESTADO_CIVIL = EMP.IND_ESTADO_CIVIL
ORDER BY 
    DEP.DESCRIPCION


SELECT DISTINCT
    DEP.ID_DEPARTAMENTO CODIGO_DEP, 
    DEP.DESCRIPCION NOMBRE_DEP
FROM 
    T_EMPLEADO EMP, 
    T_DEPARTAMENTO DEP
WHERE EMP.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
    AND EMP.IND_ESTADO_CIVIL != 0 -- 1=ACTIVO
ORDER BY 
    DEP.DESCRIPCION


SELECT DISTINCT
    DEP.ID_DEPARTAMENTO CODIGO_DEP, 
    DEP.DESCRIPCION NOMBRE_DEP,
    EMP.IND_ESTADO_CIVIL,
    CIV.NOM_ESTADO_CIVIL
FROM 
    T_ESTADO_CIVIL CIV,
    T_EMPLEADO EMP, 
    T_DEPARTAMENTO DEP
WHERE EMP.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO
    AND CIV.ID_ESTADO_CIVIL = EMP.IND_ESTADO_CIVIL
ORDER BY 
    DEP.DESCRIPCION
