---------------------------------
--- PASO N° 01 | USO DEL JOIN ---
---------------------------------

-- FORMA TRADICIONAL --
SELECT 
    EMP.FIRST_NAME, 
    EMP.DEPARTMENT_ID
FROM EMPLOYEES EMP
WHERE EMP.EMPLOYEE_ID = '150';

SELECT
    DEP.DEPARTMENT_NAME 
FROM DEPARTMENTS DEP
WHERE DEP.DEPARTMENT_ID = '80';



-- FORMA CORRECTA CON JOIN --
SELECT
    EMP.FIRST_NAME,
    DEP.DEPARTMENT_ID DEPTO,
    DEP.DEPARTMENT_NAME NOMBRE_DEPTO
FROM
    DEPARTMENTS DEP,
    EMPLOYEES EMP
WHERE EMP.EMPLOYEE_ID = '150' -- :PIN_RUT  
    AND DEP.DEPARTMENT_ID = EMP.EMPLOYEE_ID;
      