/* Ejecutar con user DPODESA */

CREATE TABLE T_EMPLEADO
(
  ID_EMPLEADO          NUMBER(10)               NOT NULL,
  COD_LOGIN            VARCHAR2(20 BYTE)        NOT NULL,
  NOMBRE_EMP           VARCHAR2(100 CHAR),
  DIRECCION_EMP        VARCHAR2(100 CHAR),
  FEC_NACIMIENTO       DATE,
  IND_ESTADO_CIVIL     NUMBER(1),
  ID_DEPARTAMENTO      NUMBER(10),
  RUT                  VARCHAR2(12 BYTE),
  DIAS_TRAB            NUMBER(2),
  EDAD                 NUMBER(2),
  IND_ESTADO_EMPLEADO  NUMBER(1)
);

COMMENT ON TABLE t_empleado IS 'datos de empleados';

COMMENT ON COLUMN t_empleado.ID_EMPLEADO	IS 'id empleado';
COMMENT ON COLUMN t_empleado.COD_LOGIN	IS 'codigo de usuario';
COMMENT ON COLUMN t_empleado.NOMBRE_EMP	IS 'nombre empleado';
COMMENT ON COLUMN t_empleado.DIRECCION_EMP	IS 'direccion del empleado';
COMMENT ON COLUMN t_empleado.FEC_NACIMIENTO	IS 'fecha de nacimiento';
COMMENT ON COLUMN t_empleado.IND_ESTADO_EMPLEADO IS 'indicador de estado del empleado';
COMMENT ON COLUMN t_empleado.ID_DEPARTAMENTO IS 'id del departamento';
COMMENT ON COLUMN t_empleado.RUT	IS 'rol unico tributario';
COMMENT ON COLUMN t_empleado.DIAS_TRAB IS 'dias trabajados';
COMMENT ON COLUMN t_empleado.EDAD	IS 'edad del empleado';
COMMENT ON COLUMN t_empleado.IND_ESTADO_EMPLEADO IS 'indicador estado del empleado';

ALTER TABLE t_empleado ADD (
  CONSTRAINT t_empleado_PK PRIMARY KEY (ID_EMPLEADO)
    USING INDEX );

SET DEFINE OFF;
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (1, 'icarreng01', 'IGNACIO CARRENO', 'LAS AVELLANAS 852, SANTIAGO', 
    TO_DATE('09/26/1979 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, 101, '12345678-9', 30, 
    21, 1);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (2, 'ccampos01', 'CARLOS DEL CAMPO', 'CALLE ARAYA 963, SAN RAMON', 
    TO_DATE('09/15/1983 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 101, '11111111-1', 31, 
    25, 1);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (3, 'jasalas01', 'JAVIERA SALAS', 'SAN FRANCISCO 8732, LA CISTERNA', 
    TO_DATE('02/11/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, 101, '22222222-2', 20, 
    30, 9);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (4, 'kglagos02', 'KLEIN LAGOS', 'LA PAMPILLA 685, LO PRADO', 
    TO_DATE('03/01/1977 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 3, 102, '33333333-3', 25, 
    35, 1);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (5, 'ymabdala03', 'YABEL DALAS', 'CALLE AGUIRRE 102, MELIPILLA', 
    TO_DATE('04/05/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 4, 102, '44444444-4', 30, 
    39, 2);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (6, 'ehmersony01', 'EMERSON YANES', 'SAN AGUSTIN 785, PUENTE ALTO', 
    TO_DATE('01/21/1974 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, 102, '55555555-5', 31, 
    37, 9);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (7, 'vhramos04', 'VALENTIN RAMOS', 'LO CAMPINO 9965, LA GRANJA', 
    TO_DATE('05/12/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 102, '66666666-6', 31, 
    27, 2);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (8, 'kbfigueroa01', 'KARLA FIGUEROA', 'ARTURO PRAT 4301, LAS CONDES', 
    TO_DATE('06/22/1971 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 103, '77777777-7', 27, 
    31, 9);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (9, 'jsguzman02', 'JAVIER GUZMAN', 'SAN CAMILO 430, BITACURA', 
    TO_DATE('06/30/1972 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 103, '88888888-8', 29, 
    27, 9);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (10, 'skmorales01', 'SANDRO MORALES', 'LO VIAL 962, ESTACION CENTRAL', 
    TO_DATE('07/15/1974 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, 103, '99999999-9', 30, 
    25, 9);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (11, 'ihcarreno02', 'ISMAEL CARREÑO', 'AVDA. SAN RAMON 751, SAN RAMON', 
    TO_DATE('08/02/1973 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 103, '1-9', 30, 
    39, 1);
Insert into T_EMPLEADO
   (ID_EMPLEADO, COD_LOGIN, NOMBRE_EMP, DIRECCION_EMP, FEC_NACIMIENTO, IND_ESTADO_CIVIL, ID_DEPARTAMENTO, RUT, DIAS_TRAB, EDAD, IND_ESTADO_EMPLEADO)
 Values
   (12, 'pqbahamon01', 'PAZ BAHAMONDE', 'LOS PLACERES 3211, LO BARNECHEA', 
    TO_DATE('09/03/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 3, 103, '2-7', 20, 
    21, 2);
COMMIT;
